name: Run semgrep
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  url: https://enxkbub0bfww1h2.m.pipedream.net
  authheader: someheader
  
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      # Fetch project source
      - uses: actions/checkout@v2

      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/gitlab-bandit

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: semgrep.sarif
      - name : curl external server
        run : |
          echo 'curl -i -X POST --insecure -H "Authorization: ${{env.authheader}}" --data "@results.sarif" ${{env.url}}'
          curl -i -X POST --insecure -H "Authorization: ${{env.authheader}}" --data "@results.sarif" ${{env.url}}
