name: Semgrep

on:
  push:
    branches: [ master, "*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

env:
  url: https://enxkbub0bfww1h2.m.pipedream.net
  authheader: someheader
  
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v2

      # Scan code using project's configuration on https://semgrep.dev/manage
      - uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: "1"
          config: p/gitlab-bandit

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()
        # curl file
      - name: curl file
        run : |
          curl -i -X POST --insecure -H "Authorization: ${{env.authheader}}" --data "@semgrep.sarif" ${{env.url}}
          ls -la
        if: always()
        
