name: Run semgrep
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  url: https://enxkbub0bfww1h2.m.pipedream.net
  authheader: someheader
  
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      # Fetch project source
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/gitlab-bandit
          
      - name: ls files
        run: ls -la
        
      - name : curl external server
        run : |
          echo 'curl -i -X POST --insecure -H "Authorization: ${{env.authheader}}" --data "@semgrep.sarif" ${{env.url}}'
          curl -i -X POST --insecure -H "Authorization: ${{env.authheader}}" --data "@semgrep.sarif" ${{env.url}}
